### ISSUE TITLE
Adapt intensity of shimmer?

### ISSUE THREAD

**Issue by nxcco** [maddyb99/shimmer_animation#16]
Is there a way to increase the intensity of the shimmer?

**Comment by maddyb99** [comment]
If I understand correctly, you want the animation to be more profound/obvious by making it more opaque, right?

If this is the case then sure, why not?

Right now the opacity is fixed to 0.1 because I imagined this to be a very subtle animation, but it can be easily modified to be passed as a parameter. This can be a good feature if this is what you were asking about!

**Comment by nxcco** [comment]
Ah okay! Yes, that was the thing I was asking for. Thanks.

**Comment by maddyb99** [comment]
Amazing, I will implement this in the evening and push it out by tonight!🥂

**Comment by nxcco** [comment]
Wow, that's fast!🤩 Wonderful! Thanks again.

**Comment by maddyb99** [comment]
Hey @nxcco ,
Would you like to try the new feature before I push it to pub.dev
I have added a new parameter called colorOpacity which can be used to set the opacity/intensity of the colour

**Comment by maddyb99** [comment]
I am closing this issue for now. 
Please feel free to reopen the same if you feel the need for improvements in this implementation or have some ideas which you think would be better!
Will push this on pub.dev soon as v2.1.0.

Cheers :clinking_glasses: and Happy Development 🙋

**Comment by nxcco** [comment]
Yes sure, I'll try it out later!
